
-- DESAFIO
-- Padronizacao e tratamento de dados de clientes
-- O QUE FOI FEITO:
-- TRIM: remove os espacos da direita e esquerda
-- ISNULL: substitui os campos NULL pelo texto NAO INFORMADO
-- UPPER: tudo em maiusculo

SELECT *
FROM TB_CLIENTES;


SELECT
(NOME)			AS NOME,
(COD_CLI)		AS CLIENTE,
(ENDERECO)		AS ENDERECO,
(CPF)			AS CPF,
(TIPO_DE_CLIENTE) AS PERFIL
FROM TB_CLIENTES;


CREATE VIEW VW_CLIENTES_TRATADOS AS
SELECT
UPPER(TRIM(NOME))			AS NOME, 	
(COD_CLI)		AS CLIENTE,
UPPER(ISNULL(TRIM(ENDERECO), 'NAO INFORMADO'))		AS ENREDECO,
(CPF)			AS CPF,
(TIPO_DE_CLIENTE)	 AS PERFIL
FROM TB_CLIENTES;



SELECT * 
FROM VW_CLIENTES_TRATADOS;
