
-- DESAFIO
-- Criar uma tabela e declarar uma variavel

SELECT * 
FROM TB_VENDAS;

CREATE TABLE TB_VENDAS_TRATADO (
DATA	DATE,
VENDEDOR	NVARCHAR(100),
QUANTIDADE	INT,
VALOR_VENDA		DECIMAL(18,2),
VALOR_PAGO	DECIMAL(18,2)
)

INSERT INTO TB_VENDAS_TRATADO

SELECT
DATA,
VENDEDOR,
QUANTIDADE,
VALOR_VENDA,
VALOR_PAGO

FROM TB_VENDAS;

SELECT * 
FROM TB_VENDAS_TRATADO;

-----------------------------------------------

DECLARE @NomeVendedor NVARCHAR(100);

SET @NomeVendedor = 'LTZ';

SELECT * 
FROM TB_VENDAS_TRATADO
WHERE VENDEDOR = @NomeVendedor;