

-- SELECT INTO
-- cria uma nova tabela a partir do resultado de um SELECT, Copia os dados
-- usado para backup e relatórios

SELECT *
FROM RELATORIO_LTZ;

SELECT *
INTO RELATORIO_LTZ
FROM TB_VENDAS
WHERE VENDEDOR = 'LTZ';

SELECT LOJA AS FILIAL,
CUPOM AS TICKET,
DATA,
COD_CLIENTE AS CLIENTE,
VENDEDOR,
QUANTIDADE,
VALOR_VENDA,
VALOR_PAGO,
VALOR_CANCELADO
INTO RELATORIO_FINAL
FROM RELATORIO_LTZ;


SELECT *
FROM RELATORIO_FINAL;