
-- DESAFIO 01
-- Criar uma tabela fisica tratando so campos com os tipos de dados

sp_help RELATORIO_LTZ;


SELECT *
FROM RELATORIO_LTZ;

CREATE TABLE RELATORIO_TRATADO(
VALOR_VENDA		DECIMAL(18,2),
DATA			DATE,
VENDEDOR		VARCHAR(100),
ANO				INT,
CUPOM			INT)

INSERT INTO RELATORIO_TRATADO

SELECT
VALOR_VENDA,
DATA,
VENDEDOR,
DATEPART (YEAR, DATA) AS ANO,
CUPOM

FROM RELATORIO_LTZ;

SELECT *
FROM RELATORIO_TRATADO;


-- DESAFIO 02
-- Criar uma view usando (SUM, FORMAT, BETWEEN, GROUP BY)

SELECT *
FROM TB_VENDAS;

DROP VIEW VW_VENDAS_TRATADO;

CREATE VIEW VW_VENDAS_TRATADO AS
SELECT 
VENDEDOR,
SUM(QUANTIDADE) AS TOTAL_PRODUTOS,
SUM(VALOR_VENDA) AS TOTAL_VENDAS
FROM TB_VENDAS
WHERE VALOR_VENDA BETWEEN 3000 AND 4000
GROUP BY VENDEDOR;

SELECT *
FROM VW_VENDAS_TRATADO
ORDER BY TOTAL_PRODUTOS ASC;	

